# Generated by Django 4.0.1 on 2022-03-28 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='_class',
            field=models.CharField(choices=[('13', '13'), ('11', '11'), ('10', '10'), ('12', '12')], max_length=5),
        ),
    ]
